apiVersion: v1
kind: Pod
metadata:
  name: serverpod
  namespace: default
spec:
  containers:
  - name: serverpod
    image: registry.cluster.wik.cloud/public/echo
    ports:
    - containerPort: 8080