version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: multi-stage.dockerfile
    ports:
      - '80'
    environment:
      - PING_LISTEN_PORT=80
    deploy:
      replicas: 4
    networks:
      - front-network

  reverse-proxy:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - front-network

networks:
  front-network:
    driver: bridge
