version: '3.8'

services:
  wordpress-db:
    container_name: wp-db
    image: bitnami/mysql:latest
    volumes:
      - 'mysql_data:/bitnami/mysql'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=mattox
      - MYSQL_DATABASE=devops
    restart: always
    networks:
      - front-network

  wordpress:
    image: bitnami/wordpress:latest
    ports:
      - '80'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mysql
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=mattox
      - WORDPRESS_DATABASE_NAME=devops
    deploy:
      replicas: 2
    depends_on:
      - wordpress-db
    networks:
      - front-network


  reverse-proxy:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress
    networks:
      - front-network

networks:
  front-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  wordpress_data:
    driver: local
